version: 2
updates:
  - commit-message:
      prefix: "chore"
    directory: /
    package-ecosystem: gomod
    schedule:
      interval: monthly
    reviewers:
      - "NorthernTechHQ/backend-dependabot-reviewers"
