version: 2
updates:
  - commit-message:
      prefix: "chore"
    directory: /
    package-ecosystem: gomod
    schedule:
      interval: monthly
  - commit-message:
      prefix: "chore"
    directory: /
    package-ecosystem: docker
    schedule:
      interval: monthly
